import type { Metadata } from "next";
import "./globals.css";
import { MouseHighlight } from "./components/mouse-highlight";
import { Header } from "./components/header";
import { JetBrains_Mono } from "next/font/google";
import { Footer } from "./components/footer";
import { Background } from "./components/background";

const jetBrainsMono = JetBrains_Mono({
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: "Leeds Computing Society",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>)
{
    return (
        <html lang="en" >
            <head>
                {/* <script
                    crossOrigin="anonymous"
                    src="//unpkg.com/react-scan/dist/auto.global.js"
                /> */}
            </head>
            <body className={jetBrainsMono.className + " absolute h-full w-full m-0 p-0 bg-brand-primary-500"}>
                <div className="absolute w-full flex flex-col overflow-hidden">
                    <Background></Background>
                    <MouseHighlight></MouseHighlight>
                    <Header></Header>
                    <div className="min-h-[100vh] flex flex-col">
                        <div className="pt-14 grow flex flex-col">
                            {children}
                        </div>
                    </div>
                    <Footer></Footer>
                </div>
            </body>
        </html>
    );
}



// <div className="min-h-full h-fit flex flex-col">
//                         <div className="mt-14 grow"></div>
{/* <div className="background">
                        <div className="background-blob-01"></div>
                        <div className="background-blob-02"></div>
                        <div className="background-blob-03"></div>
                        <MouseHighlight></MouseHighlight>
                    </div> */}
{/* <Background></Background> */ }